name: Release-Workflow
on:
  push:
    branches:
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Prepare the repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set PYTHONPATH variables
        run: |
          echo "PYTHONPATH=/home/runner/work/pyQualitas/pyQualitas" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Build the Package
        run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish Package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/